apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml

namespace: instavote

images:
- name: schoolofdevops/worker
  newTag: latest

replicas:
- name: worker
  count: 1

